"""002

Revision ID: 6dbe224da008
Revises: 086cbbd261ae
Create Date: 2023-03-15 16:15:37.640583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbe224da008'
down_revision = '086cbbd261ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_ownerid_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.drop_column('items', 'ownerid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ownerid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_ownerid_fkey', 'items', 'users', ['ownerid'], ['id'])
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
