# Generated by Django 4.0.4 on 2022-05-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phome',
            new_name='phone',
        ),
    ]
